# Generated by Django 5.2.7 on 2025-10-15 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام شرکت")),
                (
                    "economic_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="کد اقتصادی"
                    ),
                ),
                (
                    "national_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="شناسه ملی"
                    ),
                ),
                (
                    "company_type",
                    models.CharField(
                        choices=[
                            ("MANUFACTURING", "تولیدی"),
                            ("TRADING", "بازرگانی"),
                            ("SERVICE", "خدماتی"),
                            ("CONSTRUCTION", "پیمانکاری"),
                        ],
                        max_length=20,
                        verbose_name="نوع شرکت",
                    ),
                ),
                ("address", models.TextField(verbose_name="آدرس")),
                ("phone", models.CharField(max_length=15, verbose_name="تلفن")),
                ("website", models.URLField(blank=True, verbose_name="وبسایت")),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="company_logos/",
                        verbose_name="لوگو",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_companies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "شرکت\u200cها",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="CompanyInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="ایمیل دعوت شده"),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "مالک"),
                            ("ADMIN", "مدیر"),
                            ("ACCOUNTANT", "حسابدار"),
                            ("AUDITOR", "حسابرس"),
                            ("VIEWER", "مشاهده\u200cکننده"),
                        ],
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="توکن دعوت"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("ACCEPTED", "پذیرفته شده"),
                            ("REJECTED", "رد شده"),
                            ("EXPIRED", "منقضی شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="تاریخ انقضا")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations",
                        to="users.company",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دعوتنامه شرکت",
                "verbose_name_plural": "دعوتنامه\u200cهای شرکت",
            },
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام دوره")),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "is_closed",
                    models.BooleanField(default=False, verbose_name="بسته شده"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_periods",
                        to="users.company",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره مالی",
                "verbose_name_plural": "دوره\u200cهای مالی",
                "ordering": ["-start_date"],
                "unique_together": {("company", "name")},
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="users.company",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.financialperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سشن کاربر",
                "verbose_name_plural": "سشن\u200cهای کاربران",
            },
        ),
        migrations.CreateModel(
            name="UserCompanyRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("OWNER", "مالک"),
                            ("ADMIN", "مدیر"),
                            ("ACCOUNTANT", "حسابدار"),
                            ("AUDITOR", "حسابرس"),
                            ("VIEWER", "مشاهده\u200cکننده"),
                        ],
                        max_length=20,
                        verbose_name="نقش",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to="users.company",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_invitations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نقش کاربر در شرکت",
                "verbose_name_plural": "نقش\u200cهای کاربران در شرکت\u200cها",
                "unique_together": {("user", "company")},
            },
        ),
    ]
