# Generated by Django 4.2.7 on 2025-10-17 07:55

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_email_verified_company_companyinvitation_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="companyinvitation",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "دعوتنامه شرکت",
                "verbose_name_plural": "دعوتنامه\u200cهای شرکت",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "کاربر", "verbose_name_plural": "کاربران"},
        ),
        migrations.AlterModelOptions(
            name="usercompanyrole",
            options={
                "ordering": ["company", "-is_primary", "role"],
                "verbose_name": "نقش کاربر در شرکت",
                "verbose_name_plural": "نقش\u200cهای کاربران در شرکت\u200cها",
            },
        ),
        migrations.AddField(
            model_name="company",
            name="currency",
            field=models.CharField(
                choices=[("IRR", "ریال"), ("USD", "دلار"), ("EUR", "یورو")],
                default="IRR",
                max_length=10,
                verbose_name="واحد پول",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, verbose_name="توضیحات"),
        ),
        migrations.AddField(
            model_name="company",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="ایمیل"),
        ),
        migrations.AddField(
            model_name="company",
            name="fiscal_year_end",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 29, 7, 55, 17, 36048, tzinfo=datetime.timezone.utc
                ),
                verbose_name="پایان سال مالی",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="fiscal_year_start",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 1, 7, 55, 17, 35523, tzinfo=datetime.timezone.utc
                ),
                verbose_name="شروع سال مالی",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="تأیید شده"),
        ),
        migrations.AddField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی"),
        ),
        migrations.AddField(
            model_name="companyinvitation",
            name="responded_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ پاسخ"
            ),
        ),
        migrations.AddField(
            model_name="financialperiod",
            name="is_locked",
            field=models.BooleanField(default=False, verbose_name="قفل شده"),
        ),
        migrations.AddField(
            model_name="usercompanyrole",
            name="can_export_data",
            field=models.BooleanField(default=False, verbose_name="خروجی گرفتن"),
        ),
        migrations.AddField(
            model_name="usercompanyrole",
            name="can_manage_financial_data",
            field=models.BooleanField(default=False, verbose_name="مدیریت داده مالی"),
        ),
        migrations.AddField(
            model_name="usercompanyrole",
            name="can_manage_users",
            field=models.BooleanField(default=False, verbose_name="مدیریت کاربران"),
        ),
        migrations.AddField(
            model_name="usercompanyrole",
            name="can_view_reports",
            field=models.BooleanField(
                default=True, verbose_name="مشاهده گزارش\u200cها"
            ),
        ),
        migrations.AddField(
            model_name="usercompanyrole",
            name="is_primary",
            field=models.BooleanField(default=False, verbose_name="شرکت اصلی"),
        ),
        migrations.AlterField(
            model_name="company",
            name="address",
            field=models.TextField(blank=True, verbose_name="آدرس"),
        ),
        migrations.AlterField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("MANUFACTURING", "تولیدی"),
                    ("TRADING", "بازرگانی"),
                    ("SERVICE", "خدماتی"),
                    ("CONSTRUCTION", "پیمانکاری"),
                    ("HOLDING", "هلدینگ"),
                    ("OTHER", "سایر"),
                ],
                default="SERVICE",
                max_length=20,
                verbose_name="نوع شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="company",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_companies",
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="تلفن"),
        ),
        migrations.AlterField(
            model_name="companyinvitation",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="users.company",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="companyinvitation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="companyinvitation",
            name="invited_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دعوت کننده",
            ),
        ),
        migrations.AlterField(
            model_name="companyinvitation",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "مالک"),
                    ("ADMIN", "مدیر"),
                    ("ACCOUNTANT", "حسابدار"),
                    ("AUDITOR", "حسابرس"),
                    ("VIEWER", "مشاهده\u200cکننده"),
                    ("DATA_ENTRY", "تکمیل کننده داده"),
                ],
                max_length=20,
                verbose_name="نقش",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="avatars/",
                verbose_name="تصویر پروفایل",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(default=False, verbose_name="ایمیل تأیید شده"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=models.CharField(blank=True, max_length=15, verbose_name="تلفن"),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="financial_periods",
                to="users.company",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
        ),
        migrations.AlterField(
            model_name="financialperiod",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="ایجاد شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="usercompanyrole",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_roles",
                to="users.company",
                verbose_name="شرکت",
            ),
        ),
        migrations.AlterField(
            model_name="usercompanyrole",
            name="invited_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="تاریخ دعوت"),
        ),
        migrations.AlterField(
            model_name="usercompanyrole",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="دعوت شده توسط",
            ),
        ),
        migrations.AlterField(
            model_name="usercompanyrole",
            name="joined_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="تاریخ پیوستن"
            ),
        ),
        migrations.AlterField(
            model_name="usercompanyrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("OWNER", "مالک"),
                    ("ADMIN", "مدیر"),
                    ("ACCOUNTANT", "حسابدار"),
                    ("AUDITOR", "حسابرس"),
                    ("VIEWER", "مشاهده\u200cکننده"),
                    ("DATA_ENTRY", "تکمیل کننده داده"),
                ],
                max_length=20,
                verbose_name="نقش",
            ),
        ),
        migrations.AlterField(
            model_name="usercompanyrole",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_roles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="کاربر",
            ),
        ),
        migrations.AlterField(
            model_name="usersession",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_session",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(fields=["name"], name="users_compa_name_8c4c9f_idx"),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["economic_code"], name="users_compa_economi_951216_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="company",
            index=models.Index(
                fields=["is_active"], name="users_compa_is_acti_5e69e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companyinvitation",
            index=models.Index(fields=["token"], name="users_compa_token_621b87_idx"),
        ),
        migrations.AddIndex(
            model_name="companyinvitation",
            index=models.Index(fields=["status"], name="users_compa_status_45c147_idx"),
        ),
        migrations.AddIndex(
            model_name="companyinvitation",
            index=models.Index(
                fields=["expires_at"], name="users_compa_expires_a98081_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="customuser",
            table="users_customuser",
        ),
    ]
