# Generated by Django 4.2.7 on 2025-10-17 08:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_companyinvitation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="fiscal_year_end",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 29, 8, 16, 47, 203937, tzinfo=datetime.timezone.utc
                ),
                verbose_name="پایان سال مالی",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="fiscal_year_start",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 1, 8, 16, 47, 203414, tzinfo=datetime.timezone.utc
                ),
                verbose_name="شروع سال مالی",
            ),
        ),
    ]
