# Generated by Django 4.2.7 on 2025-10-20 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_company_fiscal_year_end_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="fiscal_year_end",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 12, 29, 15, 56, 7, 237206, tzinfo=datetime.timezone.utc
                ),
                verbose_name="پایان سال مالی",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="fiscal_year_start",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 1, 15, 56, 7, 237206, tzinfo=datetime.timezone.utc
                ),
                verbose_name="شروع سال مالی",
            ),
        ),
    ]
