# Generated by Django 6.0 on 2025-12-23 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_company_fiscal_year_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_end',
            field=models.DateField(default=datetime.datetime(2025, 12, 29, 17, 2, 31, 235745, tzinfo=datetime.timezone.utc), verbose_name='پایان سال مالی'),
        ),
        migrations.AlterField(
            model_name='company',
            name='fiscal_year_start',
            field=models.DateField(default=datetime.datetime(2025, 1, 1, 17, 2, 31, 235618, tzinfo=datetime.timezone.utc), verbose_name='شروع سال مالی'),
        ),
    ]
