# Generated by Django 4.2.7 on 2025-10-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChartOfAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="کد حساب")),
                ("name", models.CharField(max_length=200, verbose_name="نام حساب")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("CLASS", "کل"),
                            ("SUBCLASS", "معین"),
                            ("DETAIL", "تفصیلی"),
                            ("PROJECT", "پروژه"),
                            ("COST_CENTER", "مرکز هزینه"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.chartofaccounts",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرفصل حساب",
                "verbose_name_plural": "سرفصل\u200cهای حساب",
                "unique_together": {("code", "level")},
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="نام شرکت")),
                (
                    "economic_code",
                    models.CharField(max_length=20, verbose_name="کد اقتصادی"),
                ),
                (
                    "national_code",
                    models.CharField(max_length=20, verbose_name="شناسه ملی"),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "شرکت",
                "verbose_name_plural": "شرکت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="DocumentHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_number",
                    models.CharField(max_length=50, verbose_name="شماره سند"),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("SANAD", "سند حسابداری"),
                            ("FACTOR", "فاکتور"),
                            ("BANK", "دریافت و پرداخت بانکی"),
                            ("CASH", "دریافت و پرداخت نقدی"),
                        ],
                        max_length=20,
                    ),
                ),
                ("document_date", models.DateField(verbose_name="تاریخ سند")),
                ("description", models.TextField(verbose_name="شرح سند")),
                (
                    "total_debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                (
                    "total_credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=15),
                ),
                ("is_balanced", models.BooleanField(default=False)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "سربرگ سند",
                "verbose_name_plural": "سربرگ اسناد",
            },
        ),
        migrations.CreateModel(
            name="FinancialPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام دوره")),
                ("start_date", models.DateField(verbose_name="تاریخ شروع")),
                ("end_date", models.DateField(verbose_name="تاریخ پایان")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره مالی",
                "verbose_name_plural": "دوره\u200cهای مالی",
            },
        ),
        migrations.CreateModel(
            name="FinancialTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "پرداخت"),
                            ("RECEIPT", "دریافت"),
                            ("INVOICE", "فاکتور"),
                            ("WAREHOUSE", "رسید انبار"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=15)),
                ("transaction_date", models.DateField()),
                ("description", models.TextField()),
                ("reference_number", models.CharField(blank=True, max_length=100)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.chartofaccounts",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.company",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.financialperiod",
                    ),
                ),
            ],
            options={
                "verbose_name": "تراکنش مالی",
                "verbose_name_plural": "تراکنش\u200cهای مالی",
            },
        ),
        migrations.CreateModel(
            name="DocumentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("row_number", models.IntegerField(verbose_name="ردیف")),
                (
                    "debit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="بدهکار",
                    ),
                ),
                (
                    "credit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=15,
                        verbose_name="بستانکار",
                    ),
                ),
                ("description", models.TextField(verbose_name="شرح")),
                (
                    "cost_center",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="مرکز هزینه"
                    ),
                ),
                (
                    "project_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="کد پروژه"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financial_system.chartofaccounts",
                        verbose_name="حساب",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="financial_system.documentheader",
                    ),
                ),
            ],
            options={
                "verbose_name": "آرتیکل سند",
                "verbose_name_plural": "آرتیکل\u200cهای اسناد",
            },
        ),
        migrations.AddField(
            model_name="documentheader",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="financial_system.financialperiod",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentheader",
            unique_together={("company", "period", "document_number")},
        ),
    ]
