# Generated by Django 4.2.7 on 2025-10-25 09:22
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('financial_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.company'
            ),
        ),
        migrations.AlterField(
            model_name='financialperiod',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.company'
            ),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='company',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.company'
            ),
        ),
    ]
