# Generated by Django 4.2.7 on 2025-10-25 09:25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_company_fiscal_year_end_and_more'),
        ('financial_system', '0002_fix_company_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentheader',
            name='period',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.financialperiod'
            ),
        ),
        migrations.AlterField(
            model_name='financialtransaction',
            name='period',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='users.financialperiod'
            ),
        ),
    ]
