# Generated by Django 4.2.7 on 2025-10-25 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("financial_system", "0003_fix_period_foreign_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financialperiod",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="financial_system.company",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="financial_system.company",
            ),
        ),
        migrations.AlterField(
            model_name="financialtransaction",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="financial_system.financialperiod",
            ),
        ),
    ]
