# Generated by Django 4.2.7 on 2025-10-26 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("financial_system", "0004_alter_financialperiod_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentheader",
            name="document_date",
            field=models.CharField(max_length=10, verbose_name="تاریخ سند"),
        ),
    ]
