# Generated by Django 4.2.7 on 2025-10-24 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0010_alter_company_fiscal_year_end_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinancialFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file_name",
                    models.CharField(max_length=255, verbose_name="نام فایل"),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="نام اصلی فایل"),
                ),
                (
                    "file_path",
                    models.CharField(max_length=500, verbose_name="مسیر فایل"),
                ),
                ("file_size", models.BigIntegerField(verbose_name="حجم فایل (بایت)")),
                (
                    "software_type",
                    models.CharField(
                        choices=[
                            ("HAMKARAN", "همکاران سیستم"),
                            ("RAHKARAN", "راهکاران"),
                            ("SEPIDAR", "سپیدار"),
                            ("UNKNOWN", "ناشناخته"),
                        ],
                        default="UNKNOWN",
                        max_length=20,
                        verbose_name="نوع نرم\u200cافزار",
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(default=0.0, verbose_name="امتیاز اطمینان"),
                ),
                (
                    "columns_mapping",
                    models.JSONField(default=dict, verbose_name="نگاشت ستون\u200cها"),
                ),
                (
                    "analysis_result",
                    models.JSONField(default=dict, verbose_name="نتایج تحلیل"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("UPLOADED", "آپلود شده"),
                            ("ANALYZED", "تحلیل شده"),
                            ("VALIDATED", "اعتبارسنجی شده"),
                            ("IMPORTED", "وارد شده"),
                            ("FAILED", "خطا"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="UPLOADED",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "total_documents",
                    models.IntegerField(default=0, verbose_name="تعداد اسناد"),
                ),
                (
                    "total_items",
                    models.IntegerField(default=0, verbose_name="تعداد اقلام"),
                ),
                (
                    "validation_errors",
                    models.JSONField(default=list, verbose_name="خطاهای اعتبارسنجی"),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ آپلود"),
                ),
                (
                    "analyzed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تحلیل"
                    ),
                ),
                (
                    "imported_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ وارد کردن"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_files",
                        to="users.company",
                        verbose_name="شرکت",
                    ),
                ),
                (
                    "financial_period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="financial_files",
                        to="users.financialperiod",
                        verbose_name="دوره مالی",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="آپلود شده توسط",
                    ),
                ),
            ],
            options={
                "verbose_name": "فایل مالی",
                "verbose_name_plural": "فایل\u200cهای مالی",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="شناسه کار"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("PROCESSING", "در حال پردازش"),
                            ("COMPLETED", "تکمیل شده"),
                            ("FAILED", "خطا"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="پیشرفت (درصد)"),
                ),
                (
                    "current_step",
                    models.CharField(
                        default="آماده\u200cسازی",
                        max_length=200,
                        verbose_name="مرحله جاری",
                    ),
                ),
                (
                    "result_data",
                    models.JSONField(default=dict, verbose_name="داده\u200cهای نتیجه"),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, verbose_name="پیام خطا"),
                ),
                (
                    "stack_trace",
                    models.TextField(blank=True, verbose_name="ردیابی خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="تاریخ ایجاد"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ شروع"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تاریخ تکمیل"
                    ),
                ),
                (
                    "financial_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="data_importer.financialfile",
                        verbose_name="فایل مالی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کار وارد کردن",
                "verbose_name_plural": "کارهای وارد کردن",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="financialfile",
            index=models.Index(
                fields=["company", "status"], name="data_import_company_5c32a3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialfile",
            index=models.Index(
                fields=["uploaded_by", "uploaded_at"],
                name="data_import_uploade_50fcf0_idx",
            ),
        ),
    ]
