# Generated by Django 6.0 on 2025-12-23 17:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_importer', '0002_alter_financialfile_analysis_result'),
        ('users', '0022_alter_company_fiscal_year_end_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StandardAccountChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_code', models.CharField(max_length=50, unique=True, verbose_name='کد استاندارد')),
                ('standard_name', models.CharField(max_length=200, verbose_name='نام استاندارد')),
                ('account_type', models.CharField(choices=[('ASSET', 'دارایی'), ('LIABILITY', 'بدهی'), ('EQUITY', 'حقوق صاحبان سهام'), ('REVENUE', 'درآمد'), ('EXPENSE', 'هزینه'), ('CONTRA_ASSET', 'دارایی متقابل'), ('CONTRA_LIABILITY', 'بدهی متقابل')], max_length=20, verbose_name='نوع حساب')),
                ('level', models.IntegerField(choices=[(1, 'کل'), (2, 'معین'), (3, 'تفصیلی'), (4, 'زیر تفصیلی')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)], verbose_name='سطح')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('natural_balance', models.CharField(choices=[('DEBIT', 'بدهکار'), ('CREDIT', 'بستانکار')], max_length=10, verbose_name='تراز طبیعی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='data_importer.standardaccountchart', verbose_name='حساب والد')),
            ],
            options={
                'verbose_name': 'چارت حساب استاندارد',
                'verbose_name_plural': 'چارت حساب\u200cهای استاندارد',
                'ordering': ['level', 'standard_code'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_main_code', models.CharField(max_length=50, verbose_name='کد کل شرکت')),
                ('company_main_name', models.CharField(max_length=200, verbose_name='نام کل شرکت')),
                ('company_sub_code', models.CharField(blank=True, max_length=50, verbose_name='کد معین شرکت')),
                ('company_sub_name', models.CharField(blank=True, max_length=200, verbose_name='نام معین شرکت')),
                ('company_detail_code', models.CharField(blank=True, max_length=50, verbose_name='کد تفصیلی شرکت')),
                ('company_detail_name', models.CharField(blank=True, max_length=200, verbose_name='نام تفصیلی شرکت')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('confidence_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='امتیاز اطمینان')),
                ('mapping_type', models.CharField(choices=[('MANUAL', 'دستی'), ('AUTO_SUGGESTED', 'پیشنهاد خودکار'), ('BULK_IMPORT', 'وارد کردن دسته\u200cای')], default='MANUAL', max_length=20, verbose_name='نوع نگاشت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_mappings', to='users.company', verbose_name='شرکت')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_mappings', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('standard_detail_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detail_mappings', to='data_importer.standardaccountchart', verbose_name='کد تفصیلی استاندارد')),
                ('standard_main_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_mappings', to='data_importer.standardaccountchart', verbose_name='کد کل استاندارد')),
                ('standard_sub_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_mappings', to='data_importer.standardaccountchart', verbose_name='کد معین استاندارد')),
            ],
            options={
                'verbose_name': 'نگاشت حساب شرکت',
                'verbose_name_plural': 'نگاشت\u200cهای حساب شرکت',
                'ordering': ['company', 'company_main_code'],
            },
        ),
        migrations.CreateModel(
            name='RawFinancialData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_account_code', models.CharField(max_length=50, verbose_name='کد کل')),
                ('main_account_name', models.CharField(max_length=200, verbose_name='نام کل')),
                ('sub_account_code', models.CharField(blank=True, max_length=50, verbose_name='کد معین')),
                ('sub_account_name', models.CharField(blank=True, max_length=200, verbose_name='نام معین')),
                ('detail_account_code', models.CharField(blank=True, max_length=50, verbose_name='کد تفصیلی')),
                ('detail_account_name', models.CharField(blank=True, max_length=200, verbose_name='نام تفصیلی')),
                ('document_number', models.CharField(max_length=50, verbose_name='شماره سند')),
                ('document_date', models.DateField(verbose_name='تاریخ سند')),
                ('description', models.TextField(blank=True, verbose_name='شرح سند')),
                ('debit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بدهکار')),
                ('credit_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='مبلغ بستانکار')),
                ('row_index', models.IntegerField(verbose_name='شماره ردیف در فایل')),
                ('imported', models.BooleanField(default=False, verbose_name='وارد شده')),
                ('mapping_applied', models.BooleanField(default=False, verbose_name='نگاشت اعمال شده')),
                ('standard_main_code', models.CharField(blank=True, max_length=50, verbose_name='کد کل استاندارد')),
                ('standard_main_name', models.CharField(blank=True, max_length=200, verbose_name='نام کل استاندارد')),
                ('standard_sub_code', models.CharField(blank=True, max_length=50, verbose_name='کد معین استاندارد')),
                ('standard_sub_name', models.CharField(blank=True, max_length=200, verbose_name='نام معین استاندارد')),
                ('standard_detail_code', models.CharField(blank=True, max_length=50, verbose_name='کد تفصیلی استاندارد')),
                ('standard_detail_name', models.CharField(blank=True, max_length=200, verbose_name='نام تفصیلی استاندارد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('financial_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='data_importer.financialfile', verbose_name='فایل مالی')),
            ],
            options={
                'verbose_name': 'داده مالی خام',
                'verbose_name_plural': 'داده\u200cهای مالی خام',
                'ordering': ['financial_file', 'row_index'],
                'indexes': [models.Index(fields=['financial_file', 'imported'], name='data_import_financi_f94b48_idx'), models.Index(fields=['main_account_code'], name='data_import_main_ac_daca46_idx'), models.Index(fields=['document_number', 'document_date'], name='data_import_documen_3afea8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='standardaccountchart',
            index=models.Index(fields=['standard_code'], name='data_import_standar_433195_idx'),
        ),
        migrations.AddIndex(
            model_name='standardaccountchart',
            index=models.Index(fields=['level', 'account_type'], name='data_import_level_9f627e_idx'),
        ),
        migrations.AddIndex(
            model_name='standardaccountchart',
            index=models.Index(fields=['parent'], name='data_import_parent__b0ee04_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountmapping',
            index=models.Index(fields=['company', 'is_active'], name='data_import_company_146cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountmapping',
            index=models.Index(fields=['company_main_code'], name='data_import_company_d15d68_idx'),
        ),
        migrations.AddIndex(
            model_name='companyaccountmapping',
            index=models.Index(fields=['standard_main_code'], name='data_import_standar_755de9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='companyaccountmapping',
            unique_together={('company', 'company_main_code', 'company_sub_code', 'company_detail_code')},
        ),
    ]
